### ISSUE TITLE
Removing Spaces--Clarity

### ISSUE THREAD

**Issue by jmcdevitt100** [Bucknell-Biol364/Tutorial_Project_1#2]
I'm not sure what is meant by unnecessary spaces or extra columns-- this isn't very clear by looking at the the data printed from the line 27 code chunk. Also I might suggest that when you say like "we can now see this" maybe print the dataset again so the person getting the tutorial can prove to themselves that it worked.
https://github.com/Bucknell-Biol364/Tutorial_Project_1/blob/3acf775e411f958130606f8deaf8db4b1cb3f339/BACKUP.Rmd#L41

**Comment by sarahemooney** [comment]
I agree with Jayne.  This also confused me. When introducing a new function, I think it could be helpful to explain not only what the function does, but the arguments the function takes and what those mean. I also don't know what gsub() is personally. Maybe trimws() would've been a more intuitive approach for an intro R tutorial.
